### ISSUE TITLE
Nope.It's not working in Edge browser .:(

### ISSUE THREAD

**Issue by amitsbaghel** [FallingSnow/webp-polyfill#1]

**Comment by FallingSnow** [comment]
Next time you create an issue, please make it more useful. Try changing your title to "Not working in edge browser", adding a description of the problem, what you did, the output of the console (and there is output on why it isn't working, I just checked), and other information that will help me diagnose the issue other than, Nope not working.

**Comment by FallingSnow** [comment]
Also, it does work. You just can't run it from the local file system, needs to be running from a web server because of Edge's compulsive, over-the-top security.
![it-works](https://cloud.githubusercontent.com/assets/2512197/16427770/c011f720-3d23-11e6-8082-5bd7c6a90e55.jpg)
